[package]
name = "listenbrainz-cli-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
listenbrainz = { version = "0.7.0", git = "https://github.com/RustyNova016/listenbrainz-rs.git", branch = "main"}
musicbrainz_rs = { version = "0.5.0", features = ["blocking"], default-features = false }
derive_builder = "0.20.0"
inquire = "0.7.0"
itertools = "0.12.0"
prettytable-rs = { version = "0.10.0" }
color-eyre = "0.6.2"
rust_decimal = "1.33.1"