name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

# Copied from the dotenvy crate
# https://github.com/allan2/dotenvy/blob/master/.github/workflows/ci.yml

jobs:
  stable_tests:
    runs-on: ${{ matrix.os }}
    needs: clippy
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2
        with: 
          key: "(${{ matrix.os }})"

      - uses: taiki-e/install-action@cargo-hack

      - name: Build tests
        run: cargo hack build --feature-powerset  --ignore-private
        
      - name: Run tests
        run: cargo hack test --feature-powerset  --ignore-private

  unstable_tests:
    runs-on: ${{ matrix.os }}
    needs: stable_tests
    strategy:
      fail-fast: false
      matrix:
        rust: [beta, nightly]
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2
        with: 
          key: "(${{ matrix.rust }} - ${{ matrix.os }})"

      - uses: taiki-e/install-action@cargo-hack

      - name: Build tests
        run: cargo hack build --feature-powerset  --ignore-private
        
      - name: Run tests
        run: cargo hack test --feature-powerset  --ignore-private

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install minimal toolchain
      - name: Install minimal stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy -- -D warnings

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install minimal toolchain
      - name: Install minimal stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt --all --check

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@cargo-hack
    - run: cargo hack check --rust-version --workspace --all-targets --ignore-private
